spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-infra
    username: postgres
    password: 123456
    initialize: true
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
