# Configurações específicas para o perfil de teste (H2)
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialization-mode: always  # Garante que o H2 seja inicializado com um esquema de banco de dados
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  cors:
    allowed:
      origins: ${CORS_HOST:http://localhost:3000}
      all-methods: true
      all-headers: true
      send-credentials: true
